-- TheoGrace XMAS demo schema
-- Run in Supabase SQL Editor.

create table if not exists public.xmas_gifts (
  id bigint generated by default as identity primary key,
  public_token text unique not null,
  order_id text unique not null,
  brand text not null default 'theograce',
  customer_name text not null,
  recipient_name text not null,
  product_name text not null,
  personalization_type text not null default 'names',
  personalization jsonb not null default '[]'::jsonb,
  customer_message text,
  created_at timestamptz not null default now()
);

create index if not exists xmas_gifts_public_token_idx
  on public.xmas_gifts(public_token);

-- Direct browser access is not required.
-- The Next.js server route uses the service-role key on the server only.
alter table public.xmas_gifts enable row level security;

-- Five fictional test orders
insert into public.xmas_gifts
(public_token, order_id, brand, customer_name, recipient_name, product_name,
 personalization_type, personalization, customer_message)
values
(
 'tg-x7k2p9fa',
 'TG-10001',
 'theograce',
 'John Brown',
 'Fiona',
 'Totem 3D Bar Necklace in 10K Solid Yellow Gold',
 'names',
 '["XAVIER","JAVAUGHN","JAHMARLEY","FIONA"]'::jsonb,
 'Merry Christmas, Fiona. I chose this especially for you. Love, John'
),
(
 'tg-r4m8q2lc',
 'TG-10002',
 'theograce',
 'Emily Carter',
 'Sophie',
 'Name Necklace in Sterling Silver',
 'names',
 '["SOPHIE","EMMA"]'::jsonb,
 'A little something made especially for you. Merry Christmas!'
),
(
 'tg-b6n3v8kd',
 'TG-10003',
 'theograce',
 'Michael Davis',
 'Anna',
 'Engraved Bar Necklace',
 'dates',
 '["14.06.2018","22.09.2021","25.12.2024"]'::jsonb,
 'These dates tell our story. The real surprise is still coming.'
),
(
 'tg-h2w7c5mz',
 'TG-10004',
 'theograce',
 'Sarah Wilson',
 'Daniel',
 'Personalized Initial Pendant',
 'initials',
 '["S","D","L"]'::jsonb,
 'Merry Christmas — I hope this is worth the little extra wait.'
),
(
 'tg-p9f3j6rt',
 'TG-10005',
 'theograce',
 'David Miller',
 'Rachel',
 'Coordinates Necklace',
 'places',
 '["40.7128° N, 74.0060° W","48.8566° N, 2.3522° E"]'::jsonb,
 'Two places, a lot of memories, and one gift still on the way.'
)
on conflict (order_id) do update set
  public_token = excluded.public_token,
  customer_name = excluded.customer_name,
  recipient_name = excluded.recipient_name,
  product_name = excluded.product_name,
  personalization_type = excluded.personalization_type,
  personalization = excluded.personalization,
  customer_message = excluded.customer_message;
