'use client';
import { useEffect, useMemo, useRef, useState } from 'react';

const STORY={names:{hint:'These names will always be close to you.'},name:{hint:'One name can hold a whole story.'},dates:{hint:'Some moments deserve to stay with you.'},initials:{hint:'Sometimes the smallest details mean the most.'},places:{hint:'Some places stay with you wherever you go.'},birthstones:{hint:'A little color can hold a lot of meaning.'},words:{hint:'The right words can stay with you for a long time.'},photo:{hint:'Some memories deserve to stay close.'},mixed:{hint:'Every detail was chosen for a reason.'}};
const TIMELINE=[{start:0,end:5},{start:5,end:10},{start:10,end:17},{start:17,end:22.5},{start:22.5,end:28},{start:28,end:34},{start:34,end:40},{start:40,end:45},{start:45,end:50}];
const EXPERIENCE_DURATION=50;
function mask(value){return String(value||'').split('').map((c,i)=>/[A-Za-z0-9]/.test(c)&&i>0?'_':c).join('');}
function firstName(value){return String(value||'').trim().split(/\s+/)[0]||'Someone';}
function wheelWords(gift){const cat=String(gift.product_category||'').toLowerCase();const fam=String(gift.product_family||'').toLowerCase();if(cat.includes('bracelet'))return ['Meaning','Engraved','A memory','Made for you','A little sparkle','Personal','?'];if(fam.includes('photo')||fam.includes('locket'))return ['A memory','Someone special','Close to you','A moment','Made for you','Personal','?'];return ['Names','Memories','Engraved','A little sparkle','Made for you','Personal','?'];}
function sceneForTime(s){const i=TIMELINE.findIndex(x=>s>=x.start&&s<x.end);return i<0?TIMELINE.length-1:i;}
export default function GiftExperience({gift,details=[]}){
 const [started,setStarted]=useState(false),[scene,setScene]=useState(0),[playing,setPlaying]=useState(false);
 const audio=useRef(null),raf=useRef(null); const story=STORY[gift.personalization_type]||STORY.mixed; const giver=firstName(gift.customer_name);
 const recipient=String(gift.recipient_name||'').trim(); const hasRecipient=!!recipient; const masked=useMemo(()=>details.map(mask),[details]); const wheel=useMemo(()=>wheelWords(gift),[gift.product_category,gift.product_family]);
 useEffect(()=>()=>{if(raf.current)cancelAnimationFrame(raf.current)},[]);
 useEffect(()=>{if(!started||!audio.current)return;const tick=()=>{const a=audio.current;if(!a)return;setScene(sceneForTime(Math.max(0,a.currentTime||0)));if(!a.paused&&!a.ended)raf.current=requestAnimationFrame(tick)};if(playing)raf.current=requestAnimationFrame(tick);return()=>{if(raf.current)cancelAnimationFrame(raf.current)}},[started,playing]);
 async function begin(){const a=audio.current;setStarted(true);setScene(0);if(a){a.currentTime=0;try{await a.play();setPlaying(true)}catch{setPlaying(false)}}}
 async function togglePlayback(){const a=audio.current;if(!a)return;if(a.paused){try{await a.play();setPlaying(true)}catch{}}else{a.pause();setPlaying(false)}}
 const storyBars=TIMELINE.map((x,i)=>{if(scene>i)return 1;if(scene<i||!audio.current)return 0;return Math.max(0,Math.min(1,(audio.current.currentTime-x.start)/(x.end-x.start)))});
 return <main className="tgExperience"><audio ref={audio} src="/late-50s.m4a" preload="auto" onEnded={()=>{setPlaying(false);setScene(8)}}/>
 {!started?<section className="tgOpening tgPackagingOpening"><div className="tgOpeningGlow"/><img className="tgOfficialLogo tgOfficialLogoLight" src="/theograce-logo.svg" alt="TheoGrace"/><div className="tgOpeningContent"><div className="tgEyebrow">A CHRISTMAS MESSAGE{hasRecipient?' FOR':''}</div>{hasRecipient&&<h1>{recipient},</h1>}<p className="tgOpeningHeadline">Your Christmas gift won’t arrive in time…</p><p className="tgOpeningSub">but your gift story can still begin today.</p><div className="tgRealPackaging" aria-hidden="true"/><button className="tgOpenButton" onClick={begin}>Open my Christmas surprise <span>→</span></button><div className="tgSoundHint">♪ Turn your sound on</div></div></section>:
 <section className="tgStory" onClick={togglePlayback}><div className={`tgStoryBg tgStoryBg${scene}`}/><div className="tgStoryTop"><div className="tgBars">{TIMELINE.map((_,i)=><span key={i}><b style={{width:`${storyBars[i]*100}%`}}/></span>)}</div><img className="tgOfficialLogo tgOfficialLogoLight" src="/theograce-logo.svg" alt="TheoGrace"/><button className="tgAudioButton" onClick={e=>{e.stopPropagation();togglePlayback()}}>{playing?'Ⅱ':'▶'}</button></div>
 <div className="tgScene" key={scene}>
 {scene===0&&<><div className="tgPackagingAtmosphere"/><div className="tgEyebrow">YOUR GIFT WAS CHOSEN IN TIME</div><h2>{giver} chose something especially for you before Christmas.</h2><p>Something this personal takes a little more time to become exactly right.</p>{hasRecipient&&<div className="tgGiftTag">For {recipient}</div>}</>}
 {scene===1&&<><div className="tgPackagingAtmosphere soft"/><div className="tgEyebrow">THE GIFT BEFORE THE GIFT</div><h2>A little part of your gift is ready to be revealed.</h2><p>Not the design. Not the shape. Just a few details that belong to the real gift.</p><div className="tgGoldRule"/></>}
 {scene===2&&<><div className="tgEyebrow">CAN YOU GUESS?</div><h2>Could it be one of these?</h2><div className="tgProductWheel tgChristmasWheel" aria-label="A spinning selection of TheoGrace jewelry; it does not reveal the ordered gift"><div className="tgProductWheelPointer">▼</div><div className="tgProductOrbit">{[1,2,3,4,1,2].map((n,i)=><div className="tgWheelSlice" key={i} style={{'--i':i,'--img':`url(/wheel-product-${n}.jpg)`}}><div className="tgWheelSlicePhoto"/></div>)}<div className="tgWheelLines"/><div className="tgProductHub"><span>?</span><small>YOUR GIFT</small></div></div></div><div className="tgWheelTease"><strong>Nice try… ✨</strong><span>Your gift stays a secret.</span></div></>}
 {scene===3&&<><div className="tgChristmasJewelryHero" aria-hidden="true"><img src="/wheel-product-3.jpg"/></div><div className="tgEyebrow">A LITTLE CHRISTMAS CLUE</div><h2>But we can reveal something real…</h2>{masked.length?<div className="tgClueStack tgMasked">{masked.map((x,i)=><div className="tgClue" key={i}><small>0{i+1}</small><strong>{x}</strong></div>)}</div>:<div className="tgMemoryOrb">✦</div>}<p className="tgFine">Every clue comes from the actual gift that is still on its way.</p></>}
 {scene===4&&<><div className="tgEyebrow">A STORY IN THE DETAILS</div><h2>{details.length?`${details.length} personal ${details.length===1?'detail':'details'} were chosen for a reason.`:'Something personal is being created just for you.'}</h2><p>The real design stays a surprise until it arrives.</p><div className="tgConstellation">✦ <span>·</span> ✧ <span>·</span> ✦</div></>}
 {scene===5&&<><div className="tgEyebrow">THE REAL DETAILS</div>{details.length?<div className="tgRevealWords">{details.map((x,i)=><div className="tgRevealWord" key={i}>{x}</div>)}</div>:<div className="tgMemoryOrb">♡</div>}<p className="tgFine">These are part of the actual gift {giver} chose. The jewelry itself stays secret.</p></>}
 {scene===6&&<><div className="tgEyebrow">STILL A SECRET</div><h2>Your real gift is still under wraps.</h2><p>Chosen by {giver}.{hasRecipient&&<><br/>Created especially for {recipient}.</>}</p><div className="tgGoldRule"/><p className="tgGoldText">{story.hint}</p></>}
 {scene===7&&<div className="tgNickyCard"><div className="tgNickyPhotoWrap"><img src="/nicky.jpg" alt="Holiday message portrait"/></div><div className="tgNickyPaper"><div className="tgHandwritten">I hope this little glimpse of your gift brings a smile while you wait for the real surprise to arrive.<br/><br/>Wishing you a beautiful holiday season!</div><div className="tgNickySignature">Nicky</div><div className="tgNickyName">Nicky Hilton</div></div></div>}
 {scene===8&&<><div className="tgEyebrow">YOUR GIFT IS ON ITS WAY</div><h2 className="tgEtaTitle">Estimated delivery</h2><div className="tgEta">{gift.eta||'Monday 28'}</div><div className="tgCoupon"><small>A little something for the wait</small><strong>{gift.coupon_value||'$30'} OFF</strong><span>your next order</span><code>{gift.coupon||'XMAS30'}</code></div><button className="tgReplay" onClick={e=>{e.stopPropagation();begin()}}>Replay the experience ↻</button></>}
 </div><div className="tgTapHint">{playing?'Tap anywhere to pause':'Tap anywhere to continue'}</div></section>}</main>
}
